
export const BookCategory = [
  "Fiction",
  "Fantasy",
  "Science Fiction",
  "Mystery / Thriller",
  "Horror",
  "Romance",
  "Historical Fiction",
  "Adventure",
  "Classic Literature",
  "Poetry",
  "Biography",
  "History",
  "Science",
  "Self-Help",
  "Psychology",
  "Philosophy",
  "Religion / Spirituality",
  "Politics",
  "Travel",
  "Health & Fitness",
  "Cooking",
  "Art & Design",
  "True Crime",
  "Business",
  "Finance",
  "Economics",
  "Entrepreneurship",
  "Marketing",
  "Leadership",
  "Programming",
  "Technology",
  "Mathematics",
  "Engineering",
  "Textbook",
  "Reference",
  "Language Learning",
  "Children's Books",
  "Young Adult",
  "Comics / Graphic Novels",
  "Humor",
  "Sports",
  "Others",
];